### ISSUE TITLE
Instructions ?:D

### ISSUE THREAD

**Issue by AbhinavRobinson** [anuditnagar/pushbullet-dark#1]
How to install this, i'm noob plz help :) xoxo

**Comment by anudit** [comment]
1. Clone the repo locally.
2. Head to `chrome://extensions`.
3. Enable developer mode.
4. Go to load unpacked and select the cloned repository folder.
5. Disable your old Pushbullet.

Voila

**Comment by AbhinavRobinson** [comment]
Amazing 🤙🤙
